In [1]:
import numpy as np


In [3]:
A = np.array([1,2,3,4])
B = np.array([100,200,300,400])
condition = np.array([True,True,False,False])

# Apply Condition to Numpy using np.where(Condition, if True, if false)

In [5]:
answer2 = np.where(B<300,A,B)

In [7]:
answer2

array([  1,   2, 300, 400])

In [17]:
from numpy.random import randn
arr = randn(5,5)
np.where(arr < 0,0,arr) #Where array element is  not less than 0 replaces it by 0 else leave as it is

array([[0.00741639, 0.        , 0.6263514 , 1.91355903, 0.        ],
       [0.08891472, 0.        , 0.76873988, 0.06470303, 1.24454651],
       [0.        , 1.30150699, 0.        , 0.4534573 , 0.        ],
       [1.69006788, 0.17218192, 0.9828759 , 0.        , 1.45509307],
       [0.2576609 , 0.9073413 , 0.        , 0.44930842, 0.40979417]])

In [20]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

# Statistical Tools on numpy

In [23]:
arr.sum()

np.int64(45)

In [25]:
arr.sum(0)

array([12, 15, 18])

In [27]:
arr.mean()

np.float64(5.0)

In [29]:
arr.var()

np.float64(6.666666666666667)

In [31]:
arr.std()

np.float64(2.581988897471611)

# any() and all ()

In [34]:
bool_arr = np.array([True,False,True])

In [36]:
bool_arr.any()

np.True_

In [38]:
bool_arr.all()

np.False_

# sort(), Unique() and isin()

In [40]:
arr = randn(5,5)
arr.sort() 
np.apply_along_axis(sorted, 0, arr)

array([[-1.89846248, -1.01297025, -0.24302652,  0.16490854,  0.58967351],
       [-1.53077602, -0.44220459, -0.00328177,  0.52685642,  0.77298148],
       [-1.36252574, -0.30957619,  0.46311188,  0.87799838,  0.9354829 ],
       [-1.17486271,  0.10506221,  0.50075305,  0.99603257,  1.7629462 ],
       [-0.67121118,  0.46836797,  1.02289529,  1.66129914,  2.5497061 ]])

In [43]:
countries = np.array(['France', 'Germany', 'USA', 'Russia', 'USA', 'Mexico'])
np.unique(countries)

array(['France', 'Germany', 'Mexico', 'Russia', 'USA'], dtype='<U7')

In [47]:
np.isin(['France','USA','Sweden'],countries)

array([ True,  True, False])