# Numpy.array implementation

In [17]:
import numpy as np

my_list1 = [1, 2, 3, 4]
my_array1 = np.array(my_list1)

In [5]:
my_array1

array([1, 2, 3, 4])

In [7]:
my_list2 = [11, 22, 33, 44]
my_lists = [my_list1, my_list2]
my_array2 = np.array(my_lists)

In [9]:
my_array2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

# Finding Shape of Array

In [11]:
my_array2.shape


(2, 4)

# Data Type of Array


In [13]:
my_array2.dtype

dtype('int64')

#  Special ARRAYS in Numpy

In [15]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [17]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [19]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
np.empty((3,4))

array([[9.49872844e-312, 2.47032823e-322, 0.00000000e+000,
        0.00000000e+000],
       [6.23053953e-307, 1.58817677e-052, 5.28327832e-091,
        9.60074717e-071],
       [9.98864997e-048, 2.67610749e+184, 3.99910963e+252,
        3.73819801e-317]])

# CREATING ARRAY USING ARANGE()

In [23]:
np.arange(5,10,2)

array([5, 7, 9])

# Direct Creation

In [25]:
from __future__ import division 
arr1 = np.array([[1,2,3], [8,9,10]]) 
arr1

array([[ 1,  2,  3],
       [ 8,  9, 10]])

# Operations on ARRAY

In [27]:
arr1+arr1
arr1*arr1
arr1/arr1
arr1-arr1

array([[0, 0, 0],
       [0, 0, 0]])

# INDEXING AND SLICING


In [31]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# Slicing 

In [33]:
slice_of_arr = arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

# Replacing Sliced Element by any number

In [35]:
slice_of_arr[:]=99 
slice_of_arr

array([99, 99, 99, 99, 99, 99])

## The replacement also affects original array

In [37]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [39]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [41]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [43]:
arr_2d[[2,1]]

array([[35, 40, 45],
       [20, 25, 30]])

# The Reshape() : used to reshape in form of reshape(no. of rows, no. of Columns)

In [45]:
arr = np.arange(24).reshape((4,6)) 
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

# Transpose of any Matrix

In [47]:
arr.T

array([[ 0,  6, 12, 18],
       [ 1,  7, 13, 19],
       [ 2,  8, 14, 20],
       [ 3,  9, 15, 21],
       [ 4, 10, 16, 22],
       [ 5, 11, 17, 23]])

# dot product of two matrix

In [49]:
np.dot(arr.T,arr)

array([[504, 540, 576, 612, 648, 684],
       [540, 580, 620, 660, 700, 740],
       [576, 620, 664, 708, 752, 796],
       [612, 660, 708, 756, 804, 852],
       [648, 700, 752, 804, 856, 908],
       [684, 740, 796, 852, 908, 964]])

# 3D matrix

In [51]:
arr3d = np.arange(18).reshape((3,3,2))

In [53]:
arr3d

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]]])

# 3D Matrix Transpose

In [55]:
arr3d.transpose((1,0,2))

array([[[ 0,  1],
        [ 6,  7],
        [12, 13]],

       [[ 2,  3],
        [ 8,  9],
        [14, 15]],

       [[ 4,  5],
        [10, 11],
        [16, 17]]])

In [24]:
arr = np.arange(6)
arr

np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798])

# Array elements e^

In [26]:
np.exp(arr)

array([  1.        ,   2.71828183,   7.3890561 ,  20.08553692,
        54.59815003, 148.4131591 ])

# Array of Random Numbers

In [69]:
np.random.randn(10)

array([-0.77083596,  0.06660285, -2.03966919, -0.68493196,  0.3923546 ,
        0.09866972, -0.53130157, -1.89246241, -1.24497539, -0.53095759])